# Preprocessing

In [1]:
%run my_functions.py

[nltk_data] Downloading package stopwords to C:\Users\Annelie
[nltk_data]     Schridde\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package vader_lexicon to C:\Users\Annelie
[nltk_data]     Schridde\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
[nltk_data] Downloading package punkt to C:\Users\Annelie
[nltk_data]     Schridde\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
C:\Users\Annelie Schridde\AppData\Roaming\Python\Python38\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)

In [2]:
with open("../dataframes/raw_data.pkl", "rb") as f:
    df = pickle.load(f)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380551 entries, 0 to 380550
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   marketplace        380551 non-null  object
 1   customer_id        380551 non-null  int64
 2   review_id          380551 non-null  object
 3   product_id         380551 non-null  object
 4   product_parent     380551 non-null  int64
 5   product_title      380551 non-null  object
 6   product_category   380551 non-null  object
 7   star_rating        380551 non-null  int64
 8   helpful_votes      380551 non-null  int64
 9   total_votes        380551 non-null  int64
 10  vine               380551 non-null  object
 11  verified_purchase  380551 non-null  object
 12  review_headline    380548 non-null  object
 13  review_body        380551 non-null  object
 14  review_date        380524 non-null  object
dtypes: int64(5), object(10)
memory usage: 43.6+ MB

In [4]:
df.shape

(380551, 15)

In [5]:
df.describe()

,customer_id,product_parent,star_rating,helpful_votes,total_votes
count,3.805510e+05,3.805510e+05,380551.000000,380551.000000,380551.000000
mean,4.233049e+07,5.016846e+08,4.191512,4.818807,6.725551
std,1.250010e+07,2.888399e+08,1.223826,13.085730,15.083480
min,1.231400e+04,1.658000e+03,1.000000,0.000000,0.000000
25%,3.706371e+07,2.518290e+08,4.000000,0.000000,1.000000
50%,4.908742e+07,5.012389e+08,5.000000,2.000000,3.000000
75%,5.114276e+07,7.527070e+08,5.000000,5.000000,7.000000
max,5.309659e+07,9.999704e+08,5.000000,894.000000,1026.000000

## Verification of Sold Item

In [6]:
df.verified_purchase.value_counts()

N    284855
Y     95696
Name: verified_purchase, dtype: int64

In [7]:
df = df[df["verified_purchase"] == "Y"] # use only verified ones

In [8]:
df

,marketplace,customer_id,review_id,product_id,product_parent,product_title,product_category,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date
0,US,49033728,R1P1G5KZ05H6RD,6302503213,748506413,The Night They Saved Christmas [VHS],Video,5,0,0,N,Y,Very satisfied!!,Fast shipping. Pleasure to deal with. Would re...,2015-08-31
1,US,17857748,R106N066IUN8ZV,B000059PET,478710180,"Hamlet / Kline, New York Shakespeare Festival ...",Video,5,0,0,N,Y,The most talented actor ever!,"Kevin Kline is the most versatile, multi-talen...",2015-08-31
2,US,25551507,R7WTAA1S5O7D9,0788812807,981002815,Nascar Dual Powered Calculator (Solar & Batter...,Video,4,0,0,N,Y,Four Stars,great movie,2015-08-31
3,US,21025041,R32HFMVWLYOYJK,6302509939,333219811,"The Man From U.N.C.L.E, Volume 19: The Brain K...",Video,5,0,0,N,Y,Five Stars,i love the martin landau episode,2015-08-31
5,US,17013969,R1S3T3GWUGQTW7,6305761302,716303278,"Cabaret Balkan - (""Bure Baruta"") [VHS]",Video,5,0,0,N,Y,Five Stars,Wonderfully accurate portrayal of Serbia in th...,2015-08-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380421,US,52862670,R5ME2O91R55UK,6302098475,589476629,Robin Hood [VHS],Video,4,10,10,N,Y,A version that will keep viewers riveted!,This verison (which was first made as a theatr...,1998-01-03
380447,US,52888649,R3G1F2W978ZLW6,630460016X,388015966,Annabelle's Wish [VHS],Video,5,8,9,N,Y,A wonderful story for &quot;kids of all ages!!!,What inspired me initially to buy the video of...,1997-12-03
380468,US,52850232,RQN2844NR59MI,630349255X,345873941,Baraka [VHS],Video,5,3,4,N,Y,Terrific!!,This is a truly amazing film. I've watched it ...,1997-11-19
380513,US,52164732,RAAXE1BO6LJEY,0800196341,175290836,Hamlet [VHS],Video,5,4,5,N,Y,What a piece of work is Hamlet!,I have been fascinated by Shakespeare's &quot;...,1997-06-29
380549,US,53096413,R2TTSCG6GF6JF2,6303521517,926217354,"Wallace & Gromit: ""The Wrong Trousers""",Video,5,1,1,N,Y,Hillarious claymation thriller. For adults an...,Absolutely wonderful. This combines incredibl...,1995-12-29

In [43]:
df[pd.isna(df['review_date']) == True]

,marketplace,customer_id,review_id,product_id,product_parent,product_title,product_category,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date
31878,US,17205021,R2FCRG8KQRJN6V,0792898761,802903617,Remo Williams [VHS],Video,5,0,0,N,Y,Remo.......\t.....is INCREDIBLE! At least by ...,2013-10-20,NaN
57339,US,11660357,R13PKNKY7Z1YJG,B000EVKTCO,332561094,Disney Cartoon Classics Volumes 6 - 10 Box Set,Video,2,1,2,N,Y,I can't believe it! You still have the wrong ...,2011-06-27,NaN
60859,US,41409678,R3A6M7IF4N13D5,0783227213,553493988,Lawless Breed [VHS],Video,5,0,0,N,Y,I NEVER KILLED A MAN WHO DIDN'T TRY TO KILL ME...,2011-01-23,NaN
105433,US,44821998,R3B0A4SDFCWV7K,630166275X,798804438,Purple Heart [VHS],Video,5,17,21,N,Y,We'll come by day and we'll come by night. Tho...,2005-09-20,NaN
131191,US,52009166,R35C27J1SH41DN,6304457367,634519204,The Man Who Would Be King (Widescreen Edition)...,Video,5,2,4,N,Y,"Now, brother, how can we divide ...\t... three...",2004-03-03,NaN
177239,US,52575421,RLVIZX444O4N1,6301969588,76845203,Freaks [VHS],Video,4,3,6,N,Y,"Gooble gobble, we accept, you, one of us! one ...",2002-09-01,NaN
200723,US,47370694,RDSBXVE65SWCV,6302799171,971461982,Strait-Jacket [VHS],Video,5,0,1,N,Y,I fall to pieces...........\teach time you see...,2002-02-20,NaN
202382,US,52018723,RJJ5SQKCXH5GD,6304765096,384341371,Mitchell [VHS],Video,2,9,16,N,Y,"Do you think you are some kind of a star, like...",2002-02-08,NaN

In [46]:
from datetime import datetime
import math
df = df[pd.isna(df["review_date"]) == False]
for date in df["review_date"].astype("str"):
        datetime.strptime(date, "%Y-%M-%d")
print(df)

       marketplace  customer_id       review_id  product_id  product_parent  \
0               US     49033728  R1P1G5KZ05H6RD  6302503213       748506413
1               US     17857748  R106N066IUN8ZV  B000059PET       478710180
2               US     25551507   R7WTAA1S5O7D9  0788812807       981002815
3               US     21025041  R32HFMVWLYOYJK  6302509939       333219811
5               US     17013969  R1S3T3GWUGQTW7  6305761302       716303278
...            ...          ...             ...         ...             ...
380421          US     52862670   R5ME2O91R55UK  6302098475       589476629
380447          US     52888649  R3G1F2W978ZLW6  630460016X       388015966
380468          US     52850232   RQN2844NR59MI  630349255X       345873941
380513          US     52164732   RAAXE1BO6LJEY  0800196341       175290836
380549          US     53096413  R2TTSCG6GF6JF2  6303521517       926217354

                                            product_title product_category  \
0                    The Night They Saved Christmas [VHS]            Video
1       Hamlet / Kline, New York Shakespeare Festival ...            Video
2       Nascar Dual Powered Calculator (Solar & Batter...            Video
3       The Man From U.N.C.L.E, Volume 19: The Brain K...            Video
5                  Cabaret Balkan - ("Bure Baruta") [VHS]            Video
...                                                   ...              ...
380421                                   Robin Hood [VHS]            Video
380447                             Annabelle's Wish [VHS]            Video
380468                                       Baraka [VHS]            Video
380513                                       Hamlet [VHS]            Video
380549             Wallace & Gromit: "The Wrong Trousers"            Video

        star_rating  helpful_votes  total_votes vine verified_purchase  \
0                 5              0            0    N                 Y
1                 5              0            0    N                 Y
2                 4              0            0    N                 Y
3                 5              0            0    N                 Y
5                 5              0            0    N                 Y
...             ...            ...          ...  ...               ...
380421            4             10           10    N                 Y
380447            5              8            9    N                 Y
380468            5              3            4    N                 Y
380513            5              4            5    N                 Y
380549            5              1            1    N                 Y

                                          review_headline  \
0                                        Very satisfied!!
1                           The most talented actor ever!
2                                              Four Stars
3                                              Five Stars
5                                              Five Stars
...                                                   ...
380421          A version that will keep viewers riveted!
380447    A wonderful story for &quot;kids of all ages!!!
380468                                         Terrific!!
380513                    What a piece of work is Hamlet!
380549  Hillarious claymation thriller.  For adults an...

                                              review_body review_date
0       Fast shipping. Pleasure to deal with. Would re...  2015-08-31
1       Kevin Kline is the most versatile, multi-talen...  2015-08-31
2                                             great movie  2015-08-31
3                        i love the martin landau episode  2015-08-31
5       Wonderfully accurate portrayal of Serbia in th...  2015-08-31
...                                                   ...         ...
380421  This verison (which was first made as a theatr...  1998-01-03
380447  What inspired me initially to buy the video of...  1997-12-03
380468  This is a truly amazing film. I've watched it ...  1997-11-19
380513  I have been fascinated by Shakespeare's &quot;...  1997-06-29
380549  Absolutely wonderful.  This combines incredibl...  1995-12-29

[95688 rows x 15 columns]

In [50]:
df = df[df["review_date"] >= "2010-01-01"]

In [51]:
df["review_body_clean"] = clean_complete(df["review_body"])

D:\Master-Thesis\Code\my_functions.py:121: FutureWarning: The default value of regex will change from True to False in a future version.
  tweet = tweet.str.replace(pat, '')
D:\Master-Thesis\Code\my_functions.py:128: FutureWarning: The default value of regex will change from True to False in a future version.
  tweet = tweet.str.replace(r':-\)', ' smile')
D:\Master-Thesis\Code\my_functions.py:129: FutureWarning: The default value of regex will change from True to False in a future version.
  tweet = tweet.str.replace(r':-\(', ' sad')
D:\Master-Thesis\Code\my_functions.py:130: FutureWarning: The default value of regex will change from True to False in a future version.
  tweet = tweet.str.replace(r':-\/', ' confused')
D:\Master-Thesis\Code\my_functions.py:140: FutureWarning: The default value of regex will change from True to False in a future version.
  tweet = tweet.str.replace(r'£|\u200d|—', '')
D:\Master-Thesis\Code\my_functions.py:146: FutureWarning: The default value of regex will change from True to False in a future version.
  tweet = tweet.str.replace(r'#([^\s]+)', r'\1')
C:\Users\Annelie Schridde\AppData\Local\Temp\ipykernel_9944\1744110917.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["review_body_clean"] = clean_complete(df["review_body"])

In [52]:
def lemmatize(tweet):
    '''
    tweet: pandas series
    should be applied on the cleaned tweets to transform words to their initial base form.
    For example: suggests -> suggest, deliveries -> delivery
    '''
    nlp = spacy.load("en_core_web_sm")
    tweet = [nlp(c) for c in tweet]
    tweet = [" ".join([token.lemma_ for token in t]) for t in tweet]
    return tweet

In [53]:
df["body_lemma"] = lemmatize(df["review_body_clean"])

C:\Users\Annelie Schridde\AppData\Local\Temp\ipykernel_9944\734088808.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["body_lemma"] = lemmatize(df["review_body_clean"])

In [54]:
df['body_lemma'] = [demoji.replace(c, ' ') for c in df.body_lemma]
df['body_lemma'] = [strip_multiple_whitespaces(c) for c in df.body_lemma]

C:\Users\Annelie Schridde\AppData\Local\Temp\ipykernel_9944\719723225.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['body_lemma'] = [demoji.replace(c, ' ') for c in df.body_lemma]
C:\Users\Annelie Schridde\AppData\Local\Temp\ipykernel_9944\719723225.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['body_lemma'] = [strip_multiple_whitespaces(c) for c in df.body_lemma]

In [55]:
df["body_lemma"]

0              fast shipping pleasure deal recommend thank
1        kevin kline versatile multi talented actor mat...
2                                              great movie
3                               love martin landau episode
5             wonderfully accurate portrayal serbia ninety
                               ...
69614    love movie entertain keep interested roy schei...
69615    bump night awesome play abc saturday morning love
69616    video open music video estrange follow intervi...
69617    video little date great interview billy sheeha...
69619    pro pretty good series represent frontier day ...
Name: body_lemma, Length: 52199, dtype: object

In [56]:
df["review_head_clean"] = clean_complete(df["review_headline"].astype("str"))
df["head_lemma"] = lemmatize(df["review_head_clean"]) 
df['head_lemma'] = [demoji.replace(c, ' ') for c in df.head_lemma]
df['head_lemma'] = [strip_multiple_whitespaces(c) for c in df.head_lemma]

C:\Users\Annelie Schridde\AppData\Local\Temp\ipykernel_9944\207493426.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["review_head_clean"] = clean_complete(df["review_headline"].astype("str"))
C:\Users\Annelie Schridde\AppData\Local\Temp\ipykernel_9944\207493426.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["head_lemma"] = lemmatize(df["review_head_clean"])
C:\Users\Annelie Schridde\AppData\Local\Temp\ipykernel_9944\207493426.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['head_lemma'] = [demoji.replace(c, ' ') for c in df.head_lemma]
C:\Users\Annelie Schridde\AppData\Local\Temp\ipykernel_9944\207493426.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['head_lemma'] = [strip_multiple_whitespaces(c) for c in df.head_lemma]

In [57]:
df['head_lemma']

0                              satisfied
1                         talented actor
2                                   star
3                                   star
5                                   star
                      ...
69614                               pick
69615                               love
69616         necessity hardcore gnr fan
69617    great early billy sheehan video
69619                     hawkeye series
Name: head_lemma, Length: 52199, dtype: object

In [58]:
df["combined_clean"] = df["head_lemma"] + " " + df["body_lemma"]

C:\Users\Annelie Schridde\AppData\Local\Temp\ipykernel_9944\3947862117.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["combined_clean"] = df["head_lemma"] + " " + df["body_lemma"]

In [59]:
# the vectorizer object will be used to transform text to vector form
vectorizer = CountVectorizer(max_df=0.9, min_df=30, token_pattern='\w+|\$[\d\.]+|\S+')

# apply transformation
tf = vectorizer.fit_transform(df['combined_clean']).toarray()

# tf_feature_names tells us what word each column in the matric represents
tf_feature_names = vectorizer.get_feature_names()

In [60]:
from sklearn.decomposition import LatentDirichletAllocation

number_of_topics = 9

model = LatentDirichletAllocation(n_components=number_of_topics, random_state=0)

In [61]:
model.fit(tf)

LatentDirichletAllocation(n_components=9, random_state=0)

In [62]:
#	Calculate approximate log-likelihood as score.
model.score(tf)

-7006382.655390561

In [63]:
def display_topics(model, feature_names, no_top_words):
    """a function which takes in our model object model, the order of the words in our matrix tf_feature_names and the number of words we would like to show. Use this function, which returns a dataframe, to show you the topics we created. Remember that each topic is a list of words/tokens and weights"""
    topic_dict = {}
    for topic_idx, topic in enumerate(model.components_):
        topic_dict["Topic %d words" % (topic_idx)]= ['{}'.format(feature_names[i])
                        for i in topic.argsort()[:-no_top_words - 1:-1]]
        topic_dict["Topic %d weights" % (topic_idx)]= ['{:.1f}'.format(topic[i])
                        for i in topic.argsort()[:-no_top_words - 1:-1]]
    return pd.DataFrame(topic_dict)

In [64]:
no_top_words = 10
display_topics(model, tf_feature_names, no_top_words)

,Topic 0 words,Topic 0 weights,Topic 1 words,Topic 1 weights,Topic 2 words,Topic 2 weights,Topic 3 words,Topic 3 weights,Topic 4 words,Topic 4 weights,Topic 5 words,Topic 5 weights,Topic 6 words,Topic 6 weights,Topic 7 words,Topic 7 weights,Topic 8 words,Topic 8 weights
0,video,3822.3,vhs,7884.8,film,6157.8,video,3315.5,series,2739.2,movie,21412.9,dvd,4760.4,star,12533.4,story,1203.1
1,workout,2391.1,tape,7480.6,movie,5213.0,year,1934.4,great,2173.4,love,9396.5,version,3034.9,great,6381.0,play,1158.2
2,good,1910.8,good,3297.1,good,2749.8,watch,1346.0,book,1861.5,watch,6254.0,film,2530.2,good,5094.2,film,1100.1
3,great,1770.9,quality,2724.2,like,2592.6,love,1300.6,video,1820.7,great,5786.8,vhs,2113.9,movie,4826.7,performance,1021.1
4,tape,1606.3,condition,2619.0,story,1618.3,buy,1036.0,episode,1711.4,good,4506.1,release,1530.3,love,1958.0,john,912.4
5,work,1337.9,dvd,2522.6,time,1602.7,time,987.3,story,1311.2,old,3198.3,original,1224.1,excellent,1835.0,man,901.6
6,like,1146.6,great,2443.9,scene,1562.8,ago,973.8,history,1275.3,time,3116.3,available,1070.8,thank,1716.3,life,823.8
7,exercise,1118.1,video,2331.1,end,1553.1,see,921.2,good,1141.2,like,2919.9,movie,1064.9,story,1234.0,time,666.1
8,love,1058.8,order,2291.7,character,1490.0,song,916.5,life,907.8,enjoy,2674.8,see,773.2,classic,702.0,music,643.1
9,easy,827.1,thank,2138.3,bad,1430.6,tape,821.8,child,819.3,see,2495.2,like,762.1,nice,475.5,role,626.3